#echo REPO="stagerepo.darkpool.vip" >> /etc/darkpool/darkpool.conf
---


- name: my
  hosts: all
  become: yes
  tasks:
#  - name:  restart darkpool
##    ansible.builtin.shell:  REPO="stagerepo.darkpool.vip" 
#    lineinfile:
#      path: /etc/darkpool/darkpool.conf
#      line: 'REPO="stagerepo.darkpool.vip"'
#    register: doc
#  - debug:
#      var: doc
######
#  - name:  remove old dockers
#    ansible.builtin.shell: docker ps -aq | xargs docker stop | xargs docker rm
#    register: docker
##  - debug:
 #     var: docker
  - name:  greprepo
    ansible.builtin.shell: cat /etc/darkpool/darkpool.conf | grep REPO
    register: curl
  - debug:
      var: curl
