
---


- name: my
  hosts: all
  become: yes
  tasks:
  - name:  test_if_all_fine
    ansible.builtin.shell: docker ps
    register: doc
  - debug:
      var: doc
  - name:  curl:300
    ansible.builtin.shell: curl localhost:3000
    register: curl
  - debug:
      var: curl
