
---


- name: my
  hosts: all
  become: yes
  tasks:
  - name: darkpol restart
    ansible.builtin.shell: darkpool update
    register: doc
  - debug:
      var: doc
  - name:  docker
    ansible.builtin.shell: docker ps -a
    register: curl
  - debug:
      var: curl
